version: '2'
services:
    pokeapi-app:
        image: pokeapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pokeapi-mysql:3306/pokeapi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pokeapi-mysql:
        extends:
            file: mysql.yml
            service: pokeapi-mysql
